#server.port=8081
#server.servlet.context-path=/lucky_money

server:
  port: 8081
  servlet:
    context-path: /lucky_money

limit:
  minMoney: 1
  maxMoney: 999
  description: 最小金额为${limit.minMoney}元， 最多${limit.maxMoney}元