#server.port=8081
#server.servlet.context-path=/lucky_money

server:
  port: 8081
  servlet:
    context-path: /lucky_money

limit:
  minMoney: 0.1
  maxMoney: 999
  description: 最小金额为${limit.minMoney}元， 最多${limit.maxMoney}元

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lucky_money?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true